#!/bin/bash
set -o errexit
set -o xtrace

mkdir build
cd build

git clone --single-branch --branch master https://github.com/jupyterlab/jupyterlab.git
cd jupyterlab
git checkout 4c264b78f9e3940f278cba44e308beef6c94a04d
cd ..

git clone --single-branch --branch commenting-updates https://github.com/quansight/jupyterlab-metadata-service.git
cd jupyterlab-metadata-service
git checkout 6987b28b23e26e261cf3c496497f8a06b29dbcbc
cd backend
pip install -e .
cd jupyterlab_metadata_service_server
npm install
cd ../../..

git clone --single-branch --branch add_annotations https://github.com/jupyterlab/jupyterlab-commenting.git
cd jupyterlab-commenting
git checkout cf2a22d2d8f5675a0dc9f6bf8820af7534a7d64e
cd ..

git clone https://github.com/jupyterlab/jupyterlab-data-explorer.git
cd jupyterlab-data-explorer
git checkout 2a8e69f5863f359dceeeea80ff010e763b52c1f9
cd ..

cd jupyterlab
pip install -e .
jlpm run add:sibling ../jupyterlab-data-explorer/dataregistry
jlpm run add:sibling ../jupyterlab-data-explorer/dataregistry-extension
jlpm run add:sibling ../jupyterlab-metadata-service/frontend
jlpm run add:sibling ../jupyterlab-commenting
jlpm build:dev
jupyter lab build --dev-build=True
cd ../..
