#!/bin/bash
set -o errexit
set -o xtrace

mkdir build
cd build

git clone --single-branch --branch databus https://github.com/jupyterlab/jupyterlab.git
cd jupyterlab
git checkout 119d39472c194f9878e6bc38e5d69d6912c3379d
cd ..

git clone https://github.com/jupyterlab/jupyterlab-metadata-service.git
cd jupyterlab-metadata-service
git checkout 740ef7df5215f07fabf19f17c13efcd16c3b9a3d
cd backend
pip install -e .
cd jupyterlab_metadata_service_server
npm install
cd ../../..

git clone https://github.com/jupyterlab/jupyterlab-commenting.git
cd jupyterlab-commenting
git checkout 50657301f91b59597b07c8a0d90c97c87695ea0b
cd ..

cd jupyterlab
pip install -e .
jlpm run add:sibling ../jupyterlab-metadata-service/frontend
jlpm run add:sibling ../jupyterlab-commenting
jlpm build:dev
jupyter lab build --dev
cd ../..
